version: '3.9'

services:
  nginx:
    image: nginx:1.23.2
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./nginx/ssl/certs:/etc/ssl/certs
      - ./nginx/ssl/private:/etc/ssl/private
    network_mode: host
    # if you want to use docker networking then expose only
    # used ports
    # ports:
    #   - "80:80"
    #   - "443:443"

    # if you want get valid cert for browser check notion and use this service
    # certbot:
    #   image: certbot/certbot:latest
    #   volumes:
    #     - ./certbot/www/:/var/www/certbot/:rw
    #     - ./certbot/conf/:/etc/letsencrypt/:rw

  client:
    image: 285484/pochta_client:1.2
    # for manual testing
    # build:
    #   context: frontend
    #   dockerfile: Dockerfile
    #   args:
    #     - API_HOST=https://api.pochta-app.com
    ports:
      - 3000:3000

  mongo:
    image: mongo:6.0
    restart: always
    volumes:
      - ./backend/migrations/init.js:/docker-entrypoint-initdb.d/init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD-example}
    ports:
      - 27017:27017

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    depends_on:
      - mongo
    network_mode: host
    # ports:
    #   - 5000:5000
    environment:
      - REDIRECT_URI=http://localhost:3000/
      - CLIENT_SECRET=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
      - CLIENT_ID=1025268629997-av2ovnlbt6eipo62o1saqgc64c8s2hlo.apps.googleusercontent.com
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_PORT=27017
